[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_BUILD_CMD = "pnpm install --frozen-lockfile && pnpm build"
PORT = "5173"

# Ensure Vite can access env vars during build
VITE_OPENAI_API_KEY = "${OPENAI_API_KEY}"
VITE_ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
VITE_GROQ_API_KEY = "${GROQ_API_KEY}"
VITE_GOOGLE_GENERATIVE_AI_API_KEY = "${GOOGLE_GENERATIVE_AI_API_KEY}"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'