[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
BASE = "node:20.18.0"
DOCKERFILE_TARGET = "bolt-ai-production"
CI = "false"
NODE_ENV = "production"

[deploy]
startCommand = "pnpm run server:railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 60

[experimental]
dockerfile = true
