[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[build.args]
BASE = "node:20.18.0"
DOCKERFILE_TARGET = "bolt-ai-production"

[deploy]
startCommand = "pnpm run dockerstart"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10