[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
BASE = "node:20.18.0"
DOCKERFILE_TARGET = "bolt-ai-production"
CI = "false"

[deploy]
startCommand = "pnpm run server:simple"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[experimental]
dockerfile = true
